broken at tracker.cpp
error C4573: the usage of 'Tracker::parameters' requires the compiler to capture 'this' b
ut the current default capture mode does not allow it [C:\Users\LosWheatleynDew\source\repos\repo\April-Tag-VR-FullBody-Tracker\April-Tag-VR-FullBody-Tracker-master\final\AprilTagTrackers\AprilTagTrackers.vcxproj]

it continues on